use dm71_2

--Movies
insert into Movie values('2010-05-10', 'Apokalypto', 'Warner Brothers', '2011-03-10', '2011-03-11', '01:30:00', 'Mel Gibson', 'Postmand Per', 'Masser af aztekere') 
insert into Movie values('2010-02-05', 'Tangled', 'Disney', '2011-03-12', '2011-03-15', '01:20:00', 'Mr. McDonald', 'Postmand Per', 'Masser af aztekere')
insert into Movie values('1989-06-05', 'Die Hard', 'Disney', '2011-02-10', '2011-02-11', '04:30:01', 'Erik G', 'Erik G', 'Blablabla')

--Show
insert into Show values('01:30:00', '2010-02-05', 1)
insert into Show values('01:40:00', '2010-02-05', 2)

--Cinema
insert into Cinema values('1', 42, 6)
insert into Cinema values('2', 50, 10)
insert into Cinema values('3', 32, 4)

--Row
insert into Row values(1, 8, 1)
insert into Row values(2, 8, 1)
insert into Row values(3, 8, 1)
insert into Row values(4, 8, 1)
insert into Row values(5, 5, 1)
insert into Row values(6, 5, 1)

insert into Row values(1, 5, 2)
insert into Row values(2, 5, 2)
insert into Row values(3, 5, 2)
insert into Row values(4, 5, 2)
insert into Row values(5, 5, 2)
insert into Row values(6, 5, 2)
insert into Row values(7, 5, 2)
insert into Row values(8, 5, 2)
insert into Row values(9, 5, 2)
insert into Row values(10, 5, 2)

insert into Row values(1, 8, 3)
insert into Row values(2, 8, 3)
insert into Row values(3, 8, 3)
insert into Row values(4, 8, 3)

--Seat
insert into Seat values(1, 1, 'false', 'false')
insert into Seat values(2, 1, 'false', 'false')
insert into Seat values(3, 1, 'false', 'false')
insert into Seat values(4, 1, 'false', 'false')
insert into Seat values(5, 1, 'false', 'false')
insert into Seat values(6, 1, 'false', 'false')
insert into Seat values(7, 1, 'false', 'false')
insert into Seat values(8, 1, 'false', 'false')

insert into Seat values(1, 2, 'false', 'false')
insert into Seat values(2, 2, 'false', 'false')
insert into Seat values(3, 2, 'false', 'false')
insert into Seat values(4, 2, 'false', 'false')
insert into Seat values(5, 2, 'false', 'false')
insert into Seat values(6, 2, 'false', 'false')
insert into Seat values(7, 2, 'false', 'false')
insert into Seat values(8, 2, 'false', 'false')

insert into Seat values(1, 3, 'false', 'false')
insert into Seat values(2, 3, 'false', 'false')
insert into Seat values(3, 3, 'false', 'false')
insert into Seat values(4, 3, 'false', 'false')
insert into Seat values(5, 3, 'false', 'false')
insert into Seat values(6, 3, 'false', 'false')
insert into Seat values(7, 3, 'false', 'false')
insert into Seat values(8, 3, 'false', 'false')

insert into Seat values(1, 4, 'false', 'false')
insert into Seat values(2, 4, 'false', 'false')
insert into Seat values(3, 4, 'false', 'false')
insert into Seat values(4, 4, 'false', 'false')
insert into Seat values(5, 4, 'false', 'false')
insert into Seat values(6, 4, 'false', 'false')
insert into Seat values(7, 4, 'false', 'false')
insert into Seat values(8, 4, 'false', 'false')

insert into Seat values(1, 5, 'false', 'false')
insert into Seat values(2, 5, 'false', 'false')
insert into Seat values(3, 5, 'false', 'false')
insert into Seat values(4, 5, 'false', 'false')
insert into Seat values(5, 5, 'false', 'false')

insert into Seat values(1, 6, 'false', 'false')
insert into Seat values(2, 6, 'false', 'false')
insert into Seat values(3, 6, 'false', 'false')
insert into Seat values(4, 6, 'false', 'false')
insert into Seat values(5, 6, 'false', 'false')

insert into Seat values(1, 7, 'false', 'false')
insert into Seat values(2, 7, 'false', 'false')
insert into Seat values(3, 7, 'false', 'false')
insert into Seat values(4, 7, 'false', 'false')
insert into Seat values(5, 7, 'false', 'false')

insert into Seat values(1, 8, 'false', 'false')
insert into Seat values(2, 8, 'false', 'false')
insert into Seat values(3, 8, 'false', 'false')
insert into Seat values(4, 8, 'false', 'false')
insert into Seat values(5, 8, 'false', 'false')

insert into Seat values(1, 9, 'false', 'false')
insert into Seat values(2, 9, 'false', 'false')
insert into Seat values(3, 9, 'false', 'false')
insert into Seat values(4, 9, 'false', 'false')
insert into Seat values(5, 9, 'false', 'false')

insert into Seat values(1, 10, 'false', 'false')
insert into Seat values(2, 10, 'false', 'false')
insert into Seat values(3, 10, 'false', 'false')
insert into Seat values(4, 10, 'false', 'false')
insert into Seat values(5, 10, 'false', 'false')

insert into Seat values(1, 11, 'false', 'false')
insert into Seat values(2, 11, 'false', 'false')
insert into Seat values(3, 11, 'false', 'false')
insert into Seat values(4, 11, 'false', 'false')
insert into Seat values(5, 11, 'false', 'false')

insert into Seat values(1, 12, 'false', 'false')
insert into Seat values(2, 12, 'false', 'false')
insert into Seat values(3, 12, 'false', 'false')
insert into Seat values(4, 12, 'false', 'false')
insert into Seat values(5, 12, 'false', 'false')

insert into Seat values(1, 13, 'false', 'false')
insert into Seat values(2, 13, 'false', 'false')
insert into Seat values(3, 13, 'false', 'false')
insert into Seat values(4, 13, 'false', 'false')
insert into Seat values(5, 13, 'false', 'false')

insert into Seat values(1, 14, 'false', 'false')
insert into Seat values(2, 14, 'false', 'false')
insert into Seat values(3, 14, 'false', 'false')
insert into Seat values(4, 14, 'false', 'false')
insert into Seat values(5, 14, 'false', 'false')

insert into Seat values(1, 15, 'false', 'false')
insert into Seat values(2, 15, 'false', 'false')
insert into Seat values(3, 15, 'false', 'false')
insert into Seat values(4, 15, 'false', 'false')
insert into Seat values(5, 15, 'false', 'false')

insert into Seat values(1, 16, 'false', 'false')
insert into Seat values(2, 16, 'false', 'false')
insert into Seat values(3, 16, 'false', 'false')
insert into Seat values(4, 16, 'false', 'false')
insert into Seat values(5, 16, 'false', 'false')

insert into Seat values(1, 17, 'false', 'false')
insert into Seat values(2, 17, 'false', 'false')
insert into Seat values(3, 17, 'false', 'false')
insert into Seat values(4, 17, 'false', 'false')
insert into Seat values(5, 17, 'false', 'false')
insert into Seat values(6, 17, 'false', 'false')
insert into Seat values(7, 17, 'false', 'false')
insert into Seat values(8, 17, 'false', 'false')

insert into Seat values(1, 18, 'false', 'false')
insert into Seat values(2, 18, 'false', 'false')
insert into Seat values(3, 18, 'false', 'false')
insert into Seat values(4, 18, 'false', 'false')
insert into Seat values(5, 18, 'false', 'false')
insert into Seat values(6, 18, 'false', 'false')
insert into Seat values(7, 18, 'false', 'false')
insert into Seat values(8, 18, 'false', 'false')

insert into Seat values(1, 19, 'false', 'false')
insert into Seat values(2, 19, 'false', 'false')
insert into Seat values(3, 19, 'false', 'false')
insert into Seat values(4, 19, 'false', 'false')
insert into Seat values(5, 19, 'false', 'false')
insert into Seat values(6, 19, 'false', 'false')
insert into Seat values(7, 19, 'false', 'false')
insert into Seat values(8, 19, 'false', 'false')

insert into Seat values(1, 20, 'false', 'false')
insert into Seat values(2, 20, 'false', 'false')
insert into Seat values(3, 20, 'false', 'false')
insert into Seat values(4, 20, 'false', 'false')
insert into Seat values(5, 20, 'false', 'false')
insert into Seat values(6, 20, 'false', 'false')
insert into Seat values(7, 20, 'false', 'false')
insert into Seat values(8, 20, 'false', 'false')

--Cinema_Show
insert into Cinema_Show values(1, 1)
insert into Cinema_Show values(2, 2)
insert into Cinema_Show values(2, 1)
insert into Cinema_Show values(1, 2)