//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemaXP_WCFServiceLib.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/TemaXP_Groupe1_WcfService1.ModelLayer")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrivalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Actors {
            get {
                return this.ActorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ActorsField, value) != true)) {
                    this.ActorsField = value;
                    this.RaisePropertyChanged("Actors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArrivalDate {
            get {
                return this.ArrivalDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalDateField, value) != true)) {
                    this.ArrivalDateField = value;
                    this.RaisePropertyChanged("ArrivalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Director {
            get {
                return this.DirectorField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectorField, value) != true)) {
                    this.DirectorField = value;
                    this.RaisePropertyChanged("Director");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distributor {
            get {
                return this.DistributorField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributorField, value) != true)) {
                    this.DistributorField = value;
                    this.RaisePropertyChanged("Distributor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((object.ReferenceEquals(this.DurationField, value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieDescription {
            get {
                return this.MovieDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieDescriptionField, value) != true)) {
                    this.MovieDescriptionField = value;
                    this.RaisePropertyChanged("MovieDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReleaseDateField, value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnDateField, value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/FindMovieByTitle", ReplyAction="http://tempuri.org/IService2/FindMovieByTitleResponse")]
        TemaXP_WCFServiceLib.ServiceReference1.Movie FindMovieByTitle(string title, bool retrieveAssociation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/FindMovieById", ReplyAction="http://tempuri.org/IService2/FindMovieByIdResponse")]
        TemaXP_WCFServiceLib.ServiceReference1.Movie FindMovieById(TemaXP_WCFServiceLib.ServiceReference1.Movie m, bool retrieveAssociation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/InsertMovie", ReplyAction="http://tempuri.org/IService2/InsertMovieResponse")]
        void InsertMovie(string releaseDate, string title, string distributor, string arrivalDate, string returnDate, string duration, string director, string actors, string movieDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/UpdateMovie", ReplyAction="http://tempuri.org/IService2/UpdateMovieResponse")]
        void UpdateMovie(string currentTitle, string releaseDate, string title, string distributor, string arrivalDate, string returnDate, string duration, string director, string actors, string movieDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/DeleteMovie", ReplyAction="http://tempuri.org/IService2/DeleteMovieResponse")]
        void DeleteMovie(TemaXP_WCFServiceLib.ServiceReference1.Movie m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/FindAllMovies", ReplyAction="http://tempuri.org/IService2/FindAllMoviesResponse")]
        TemaXP_WCFServiceLib.ServiceReference1.Movie[] FindAllMovies(bool retrieveAssociation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : TemaXP_WCFServiceLib.ServiceReference1.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<TemaXP_WCFServiceLib.ServiceReference1.IService2>, TemaXP_WCFServiceLib.ServiceReference1.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TemaXP_WCFServiceLib.ServiceReference1.Movie FindMovieByTitle(string title, bool retrieveAssociation) {
            return base.Channel.FindMovieByTitle(title, retrieveAssociation);
        }
        
        public TemaXP_WCFServiceLib.ServiceReference1.Movie FindMovieById(TemaXP_WCFServiceLib.ServiceReference1.Movie m, bool retrieveAssociation) {
            return base.Channel.FindMovieById(m, retrieveAssociation);
        }
        
        public void InsertMovie(string releaseDate, string title, string distributor, string arrivalDate, string returnDate, string duration, string director, string actors, string movieDescription) {
            base.Channel.InsertMovie(releaseDate, title, distributor, arrivalDate, returnDate, duration, director, actors, movieDescription);
        }
        
        public void UpdateMovie(string currentTitle, string releaseDate, string title, string distributor, string arrivalDate, string returnDate, string duration, string director, string actors, string movieDescription) {
            base.Channel.UpdateMovie(currentTitle, releaseDate, title, distributor, arrivalDate, returnDate, duration, director, actors, movieDescription);
        }
        
        public void DeleteMovie(TemaXP_WCFServiceLib.ServiceReference1.Movie m) {
            base.Channel.DeleteMovie(m);
        }
        
        public TemaXP_WCFServiceLib.ServiceReference1.Movie[] FindAllMovies(bool retrieveAssociation) {
            return base.Channel.FindAllMovies(retrieveAssociation);
        }
    }
}
