#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using TemaXP_DM71_Group1;
using Telerik.OpenAccess.Metadata;


namespace TemaXP_DM71_Group1	
{	
	public partial class TemaXP_DM71_2 : OpenAccessContext
	{
		private static string connectionStringName = "TemaXP_DM71_2";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("BioGroup1.rlinq");
	
		public TemaXP_DM71_2()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public TemaXP_DM71_2(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public TemaXP_DM71_2(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public TemaXP_DM71_2(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public TemaXP_DM71_2(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Film> Films 
		{
	    	get
	    	{
	        	return this.GetAll<Film>();
	    	}
		}
		
		public IQueryable<Test> Tests 
		{
	    	get
	    	{
	        	return this.GetAll<Test>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "mssql";
			return backend;
		}
	}
}
#pragma warning restore 1591
