#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;


namespace TemaXP_DM71_Group1	
{
	public partial class Cinema_Show
	{
		private int id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this.id;
		    }
		    set
		    {
		        this.id = value;
		    }
		}
		
		private int showID;
		public virtual int ShowID 
		{ 
		    get
		    {
		        return this.showID;
		    }
		    set
		    {
		        this.showID = value;
		    }
		}
		
		private int cinemaID;
		public virtual int CinemaID 
		{ 
		    get
		    {
		        return this.cinemaID;
		    }
		    set
		    {
		        this.cinemaID = value;
		    }
		}
		
		private Cinema cinema;
		public virtual Cinema Cinema 
		{ 
		    get
		    {
		        return this.cinema;
		    }
		    set
		    {
		        this.cinema = value;
		    }
		}
		
		private Show show;
		public virtual Show Show 
		{ 
		    get
		    {
		        return this.show;
		    }
		    set
		    {
		        this.show = value;
		    }
		}
		
	}
}
