#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;


namespace TemaXP_DM71_Group1	
{
	public partial class Cinema
	{
		private int id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this.id;
		    }
		    set
		    {
		        this.id = value;
		    }
		}
		
		private int noOfCinema;
		public virtual int NoOfCinema 
		{ 
		    get
		    {
		        return this.noOfCinema;
		    }
		    set
		    {
		        this.noOfCinema = value;
		    }
		}
		
		private int noOfSeats;
		public virtual int NoOfSeats 
		{ 
		    get
		    {
		        return this.noOfSeats;
		    }
		    set
		    {
		        this.noOfSeats = value;
		    }
		}
		
		private IList<Cinema_Show> cinemaShows = new List<Cinema_Show>();
		public virtual IList<Cinema_Show> Cinema_Shows 
		{ 
		    get
		    {
		        return this.cinemaShows;
		    }
		}
		
	}
}
