#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;


namespace TemaXP_DM71_Group1	
{
	public partial class Show
	{
		private int id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this.id;
		    }
		    set
		    {
		        this.id = value;
		    }
		}
		
		private DateTime playtime;
		public virtual DateTime Playtime 
		{ 
		    get
		    {
		        return this.playtime;
		    }
		    set
		    {
		        this.playtime = value;
		    }
		}
		
		private DateTime date_;
		public virtual DateTime Date_ 
		{ 
		    get
		    {
		        return this.date_;
		    }
		    set
		    {
		        this.date_ = value;
		    }
		}
		
		private string cinema;
		public virtual string Cinema 
		{ 
		    get
		    {
		        return this.cinema;
		    }
		    set
		    {
		        this.cinema = value;
		    }
		}
		
		private string movie;
		public virtual string Movie 
		{ 
		    get
		    {
		        return this.movie;
		    }
		    set
		    {
		        this.movie = value;
		    }
		}
		
		private int movieId;
		public virtual int MovieId 
		{ 
		    get
		    {
		        return this.movieId;
		    }
		    set
		    {
		        this.movieId = value;
		    }
		}
		
		private Film film;
		public virtual Film Film 
		{ 
		    get
		    {
		        return this.film;
		    }
		    set
		    {
		        this.film = value;
		    }
		}
		
	}
}
