//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemaXP_DM71_Group1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindCinemaByName", ReplyAction="http://tempuri.org/IService1/FindCinemaByNameResponse")]
        TemaXP_WCFServiceLib.ModelLayer.Cinema FindCinemaByName(string cinemaName, bool retrieveAssociation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindAllCinemas", ReplyAction="http://tempuri.org/IService1/FindAllCinemasResponse")]
        TemaXP_WCFServiceLib.ModelLayer.Cinema[] FindAllCinemas(bool retrieveAssociation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCinema", ReplyAction="http://tempuri.org/IService1/InsertCinemaResponse")]
        void InsertCinema(string cinemaName, int noOfRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSeatsToRow", ReplyAction="http://tempuri.org/IService1/AddSeatsToRowResponse")]
        void AddSeatsToRow(TemaXP_WCFServiceLib.ModelLayer.Cinema c, int rowNumber, int noOfSeats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCinema", ReplyAction="http://tempuri.org/IService1/UpdateCinemaResponse")]
        void UpdateCinema(TemaXP_WCFServiceLib.ModelLayer.Cinema c, string cinemaName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCinema", ReplyAction="http://tempuri.org/IService1/DeleteCinemaResponse")]
        void DeleteCinema(TemaXP_WCFServiceLib.ModelLayer.Cinema c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindMovieByTitle", ReplyAction="http://tempuri.org/IService1/FindMovieByTitleResponse")]
        TemaXP_WCFServiceLib.ModelLayer.Movie FindMovieByTitle(string title, bool retrieveAssociation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindMovieById", ReplyAction="http://tempuri.org/IService1/FindMovieByIdResponse")]
        TemaXP_WCFServiceLib.ModelLayer.Movie FindMovieById(TemaXP_WCFServiceLib.ModelLayer.Movie m, bool retrieveAssociation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMovie", ReplyAction="http://tempuri.org/IService1/InsertMovieResponse")]
        void InsertMovie(string releaseDate, string title, string distributor, string arrivalDate, string returnDate, string duration, string director, string actors, string movieDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMovie", ReplyAction="http://tempuri.org/IService1/UpdateMovieResponse")]
        void UpdateMovie(string currentTitle, string releaseDate, string title, string distributor, string arrivalDate, string returnDate, string duration, string director, string actors, string movieDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMovie", ReplyAction="http://tempuri.org/IService1/DeleteMovieResponse")]
        void DeleteMovie(TemaXP_WCFServiceLib.ModelLayer.Movie m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindAllMovies", ReplyAction="http://tempuri.org/IService1/FindAllMoviesResponse")]
        TemaXP_WCFServiceLib.ModelLayer.Movie[] FindAllMovies(bool retrieveAssociation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertShow", ReplyAction="http://tempuri.org/IService1/InsertShowResponse")]
        void InsertShow(string movieStartTime, string showDate, TemaXP_WCFServiceLib.ModelLayer.Movie movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteShow", ReplyAction="http://tempuri.org/IService1/DeleteShowResponse")]
        void DeleteShow(TemaXP_WCFServiceLib.ModelLayer.Show s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateShow", ReplyAction="http://tempuri.org/IService1/UpdateShowResponse")]
        void UpdateShow(TemaXP_WCFServiceLib.ModelLayer.Show s, string movieStartTime, string showDate, TemaXP_WCFServiceLib.ModelLayer.Movie movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindAllShows", ReplyAction="http://tempuri.org/IService1/FindAllShowsResponse")]
        TemaXP_WCFServiceLib.ModelLayer.Show[] FindAllShows(bool retrieveAssociation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindShowByMovieId", ReplyAction="http://tempuri.org/IService1/FindShowByMovieIdResponse")]
        TemaXP_WCFServiceLib.ModelLayer.Show FindShowByMovieId(TemaXP_WCFServiceLib.ModelLayer.Movie m, bool retrieveAssociation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindShowByMovieIdAndShowDate", ReplyAction="http://tempuri.org/IService1/FindShowByMovieIdAndShowDateResponse")]
        TemaXP_WCFServiceLib.ModelLayer.Show FindShowByMovieIdAndShowDate(TemaXP_WCFServiceLib.ModelLayer.Movie m, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllShowsOneWeekAhead", ReplyAction="http://tempuri.org/IService1/GetAllShowsOneWeekAheadResponse")]
        TemaXP_WCFServiceLib.ModelLayer.Show[] GetAllShowsOneWeekAhead(bool retrieveAssociation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TemaXP_DM71_Group1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TemaXP_DM71_Group1.ServiceReference1.IService1>, TemaXP_DM71_Group1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TemaXP_WCFServiceLib.ModelLayer.Cinema FindCinemaByName(string cinemaName, bool retrieveAssociation) {
            return base.Channel.FindCinemaByName(cinemaName, retrieveAssociation);
        }
        
        public TemaXP_WCFServiceLib.ModelLayer.Cinema[] FindAllCinemas(bool retrieveAssociation) {
            return base.Channel.FindAllCinemas(retrieveAssociation);
        }
        
        public void InsertCinema(string cinemaName, int noOfRows) {
            base.Channel.InsertCinema(cinemaName, noOfRows);
        }
        
        public void AddSeatsToRow(TemaXP_WCFServiceLib.ModelLayer.Cinema c, int rowNumber, int noOfSeats) {
            base.Channel.AddSeatsToRow(c, rowNumber, noOfSeats);
        }
        
        public void UpdateCinema(TemaXP_WCFServiceLib.ModelLayer.Cinema c, string cinemaName) {
            base.Channel.UpdateCinema(c, cinemaName);
        }
        
        public void DeleteCinema(TemaXP_WCFServiceLib.ModelLayer.Cinema c) {
            base.Channel.DeleteCinema(c);
        }
        
        public TemaXP_WCFServiceLib.ModelLayer.Movie FindMovieByTitle(string title, bool retrieveAssociation) {
            return base.Channel.FindMovieByTitle(title, retrieveAssociation);
        }
        
        public TemaXP_WCFServiceLib.ModelLayer.Movie FindMovieById(TemaXP_WCFServiceLib.ModelLayer.Movie m, bool retrieveAssociation) {
            return base.Channel.FindMovieById(m, retrieveAssociation);
        }
        
        public void InsertMovie(string releaseDate, string title, string distributor, string arrivalDate, string returnDate, string duration, string director, string actors, string movieDescription) {
            base.Channel.InsertMovie(releaseDate, title, distributor, arrivalDate, returnDate, duration, director, actors, movieDescription);
        }
        
        public void UpdateMovie(string currentTitle, string releaseDate, string title, string distributor, string arrivalDate, string returnDate, string duration, string director, string actors, string movieDescription) {
            base.Channel.UpdateMovie(currentTitle, releaseDate, title, distributor, arrivalDate, returnDate, duration, director, actors, movieDescription);
        }
        
        public void DeleteMovie(TemaXP_WCFServiceLib.ModelLayer.Movie m) {
            base.Channel.DeleteMovie(m);
        }
        
        public TemaXP_WCFServiceLib.ModelLayer.Movie[] FindAllMovies(bool retrieveAssociation) {
            return base.Channel.FindAllMovies(retrieveAssociation);
        }
        
        public void InsertShow(string movieStartTime, string showDate, TemaXP_WCFServiceLib.ModelLayer.Movie movie) {
            base.Channel.InsertShow(movieStartTime, showDate, movie);
        }
        
        public void DeleteShow(TemaXP_WCFServiceLib.ModelLayer.Show s) {
            base.Channel.DeleteShow(s);
        }
        
        public void UpdateShow(TemaXP_WCFServiceLib.ModelLayer.Show s, string movieStartTime, string showDate, TemaXP_WCFServiceLib.ModelLayer.Movie movie) {
            base.Channel.UpdateShow(s, movieStartTime, showDate, movie);
        }
        
        public TemaXP_WCFServiceLib.ModelLayer.Show[] FindAllShows(bool retrieveAssociation) {
            return base.Channel.FindAllShows(retrieveAssociation);
        }
        
        public TemaXP_WCFServiceLib.ModelLayer.Show FindShowByMovieId(TemaXP_WCFServiceLib.ModelLayer.Movie m, bool retrieveAssociation) {
            return base.Channel.FindShowByMovieId(m, retrieveAssociation);
        }
        
        public TemaXP_WCFServiceLib.ModelLayer.Show FindShowByMovieIdAndShowDate(TemaXP_WCFServiceLib.ModelLayer.Movie m, string date) {
            return base.Channel.FindShowByMovieIdAndShowDate(m, date);
        }
        
        public TemaXP_WCFServiceLib.ModelLayer.Show[] GetAllShowsOneWeekAhead(bool retrieveAssociation) {
            return base.Channel.GetAllShowsOneWeekAhead(retrieveAssociation);
        }
    }
}
